### ISSUE TITLE
Crash when attacking player with Nightblood

### ISSUE THREAD

**Issue by madeline0706** [Quplet/Qu-Enchantments#3]
Hi, so a player of mine found out the hard way that using a Nightblood sword against another player crashes the server, it freezes the whole server for over a minute, and does not let the server save either, resulting in a loss of progress whenever it happens

I am using qu-enchantments-1.1.1-1.19.jar on Fabric 1.19

this is the log that came out

[26.06 10:04:23] [Server] [Server Watchdog/ERROR]: A single server tick took 60.00 seconds (should be max 0.05)
[26.06 10:04:23] [Server] [Server Watchdog/ERROR]: Considering it to be crashed, server will forcibly shutdown.
[26.06 10:04:24] [Server] Crash report:
[26.06 10:04:24] [Server] ---- Minecraft Crash Report ----
[26.06 10:04:24] [Server] // I blame Dinnerbone.
[26.06 10:04:24] [Server] Time6/26/22, 1:04 PM
[26.06 10:04:24] [Server] DescriptionWatching Server
[26.06 10:04:24] [Server] java.lang.ErrorWatchdog
[26.06 10:04:24] [Server] 	at net.minecraft.class_1799.method_7970(class_1799.java:334)
[26.06 10:04:24] [Server] 	at net.minecraft.class_1799.method_7956(class_1799.java:367)
[26.06 10:04:24] [Server] 	at net.minecraft.class_1661.method_7375(class_1661.java:530)
[26.06 10:04:24] [Server] 	at net.minecraft.class_1657.method_6105(class_1657.java:983)
[26.06 10:04:24] [Server] 	at net.minecraft.class_1309.redirect$zbc000$preventArmorDamaging(class_1309.java:4813)
[26.06 10:04:24] [Server] 	at net.minecraft.class_1309.method_6132(class_1309.java:1607)
[26.06 10:04:24] [Server] 	at net.minecraft.class_1657.method_6074(class_1657.java:1021)
[26.06 10:04:24] [Server] 	at net.minecraft.class_1309.method_5643(class_1309.java:1120)
[26.06 10:04:24] [Server] 	at net.minecraft.class_1657.method_5643(class_1657.java:951)
[26.06 10:04:24] [Server] 	at net.minecraft.class_3222.method_5643(class_3222.java:713)
[26.06 10:04:24] [Server] 	at qu.quEnchantments.enchantments.NightbloodEnchantment.method_8189(NightbloodEnchantment.java:48)
[26.06 10:04:24] [Server] 	at net.minecraft.class_1890.method_8207(class_1890.java:179)
[26.06 10:04:24] [Server] 	at net.minecraft.class_1890$$Lambda$8950/0x00000008020cad78.accept(Unknown Source)
[26.06 10:04:24] [Server] 	at net.minecraft.class_1890.method_17883(class_1890.java:138)
[26.06 10:04:24] [Server] 	at net.minecraft.class_1890$$Lambda$8854/0x00000008020b6698.accept(Unknown Source)
[26.06 10:04:24] [Server] 	at java.base@17.0.1/java.util.Optional.ifPresent(Optional.java:178)
[26.06 10:04:24] [Server] 	at net.minecraft.class_1890.method_8220(class_1890.java:138)
[26.06 10:04:24] [Server] 	at net.minecraft.class_1890.method_8209(class_1890.java:144)
[26.06 10:04:24] [Server] 	at net.minecraft.class_1890.method_8213(class_1890.java:181)
[26.06 10:04:24] [Server] 	at net.minecraft.class_1657.method_7324(class_1657.java:1341)
[26.06 10:04:24] [Server] 	at net.minecraft.class_3222.method_7324(class_3222.java:1468)
[26.06 10:04:24] [Server] 	at net.minecraft.class_3244$1.method_34218(class_3244.java:1538)
[26.06 10:04:24] [Server] 	at net.minecraft.class_2824$1.method_34213(class_2824.java:166)
[26.06 10:04:24] [Server] 	at net.minecraft.class_2824.method_34209(class_2824.java:66)
[26.06 10:04:24] [Server] 	at net.minecraft.class_3244.method_12062(class_3244.java:1508)
[26.06 10:04:24] [Server] 	at net.minecraft.class_2824.method_12251(class_2824.java:53)
[26.06 10:04:24] [Server] 	at net.minecraft.class_2824.method_11054(class_2824.java:13)
[26.06 10:04:24] [Server] 	at net.minecraft.class_2600.method_11072(class_2600.java:22)
[26.06 10:04:24] [Server] 	at net.minecraft.class_2600$$Lambda$8191/0x0000000801ff5f08.run(Unknown Source)
[26.06 10:04:24] [Server] 	at net.minecraft.class_3738.run(class_3738.java:18)
[26.06 10:04:24] [Server] 	at net.minecraft.class_1255.method_18859(class_1255.java:157)
[26.06 10:04:24] [Server] 	at net.minecraft.class_4093.method_18859(class_4093.java:23)
[26.06 10:04:24] [Server] 	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776)
[26.06 10:04:24] [Server] 	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:160)
[26.06 10:04:24] [Server] 	at net.minecraft.class_1255.method_16075(class_1255.java:131)
[26.06 10:04:24] [Server] 	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758)
[26.06 10:04:24] [Server] 	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752)
[26.06 10:04:24] [Server] 	at net.minecraft.class_1255.method_5383(class_1255.java:116)
[26.06 10:04:24] [Server] 	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:736)
[26.06 10:04:24] [Server] 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669)
[26.06 10:04:24] [Server] 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258)
[26.06 10:04:24] [Server] 	at net.minecraft.server.MinecraftServer$$Lambda$6457/0x0000000801aec000.run(Unknown Source)
[26.06 10:04:24] [Server] 	at java.base@17.0.1/java.lang.Thread.run(Thread.java:833)
[26.06 10:04:24] [Server] A detailed walkthrough of the error, its code path and all known details is as follows:
[26.06 10:04:24] [Server] ---------------------------------------------------------------------------------------
[26.06 10:04:24] [Server] -- Head --
[26.06 10:04:24] [Server] ThreadServer Watchdog
[26.06 10:04:24] [Server] Stacktrace:
[26.06 10:04:24] [Server] 	at net.minecraft.class_1799.method_7970(class_1799.java:334)
[26.06 10:04:24] [Server] 	at net.minecraft.class_1799.method_7956(class_1799.java:367)
[26.06 10:04:24] [Server] 	at net.minecraft.class_1661.method_7375(class_1661.java:530)
[26.06 10:04:24] [Server] 	at net.minecraft.class_1657.method_6105(class_1657.java:983)
[26.06 10:04:24] [Server] 	at net.minecraft.class_1309.redirect$zbc000$preventArmorDamaging(class_1309.java:4813)
[26.06 10:04:24] [Server] 	at net.minecraft.class_1309.method_6132(class_1309.java:1607)
[26.06 10:04:24] [Server] 	at net.minecraft.class_1657.method_6074(class_1657.java:1021)
[26.06 10:04:24] [Server] 	at net.minecraft.class_1309.method_5643(class_1309.java:1120)
[26.06 10:04:24] [Server] 	at net.minecraft.class_1657.method_5643(class_1657.java:951)
[26.06 10:04:24] [Server] 	at net.minecraft.class_3222.method_5643(class_3222.java:713)
[26.06 10:04:24] [Server] 	at qu.quEnchantments.enchantments.NightbloodEnchantment.method_8189(NightbloodEnchantment.java:48)
[26.06 10:04:24] [Server] 	at net.minecraft.class_1890.method_8207(class_1890.java:179)
[26.06 10:04:24] [Server] 	at net.minecraft.class_1890$$Lambda$8950/0x00000008020cad78.accept(Unknown Source)
[26.06 10:04:24] [Server] 	at net.minecraft.class_1890.method_17883(class_1890.java:138)
[26.06 10:04:24] [Server] 	at net.minecraft.class_1890$$Lambda$8854/0x00000008020b6698.accept(Unknown Source)
[26.06 10:04:24] [Server] 	at java.base@17.0.1/java.util.Optional.ifPresent(Optional.java:178)
[26.06 10:04:24] [Server] 	at net.minecraft.class_1890.method_8220(class_1890.java:138)
[26.06 10:04:24] [Server] 	at net.minecraft.class_1890.method_8209(class_1890.java:144)
[26.06 10:04:24] [Server] 	at net.minecraft.class_1890.method_8213(class_1890.java:181)
[26.06 10:04:24] [Server] 	at net.minecraft.class_1657.method_7324(class_1657.java:1341)
[26.06 10:04:24] [Server] 	at net.minecraft.class_3222.method_7324(class_3222.java:1468)
[26.06 10:04:24] [Server] 	at net.minecraft.class_3244$1.method_34218(class_3244.java:1538)
[26.06 10:04:24] [Server] 	at net.minecraft.class_2824$1.method_34213(class_2824.java:166)
[26.06 10:04:24] [Server] 	at net.minecraft.class_2824.method_34209(class_2824.java:66)
[26.06 10:04:24] [Server] 	at net.minecraft.class_3244.method_12062(class_3244.java:1508)
[26.06 10:04:24] [Server] 	at net.minecraft.class_2824.method_12251(class_2824.java:53)
[26.06 10:04:24] [Server] 	at net.minecraft.class_2824.method_11054(class_2824.java:13)
[26.06 10:04:24] [Server] 	at net.minecraft.class_2600.method_11072(class_2600.java:22)
[26.06 10:04:24] [Server] 	at net.minecraft.class_2600$$Lambda$8191/0x0000000801ff5f08.run(Unknown Source)
[26.06 10:04:24] [Server] 	at net.minecraft.class_3738.run(class_3738.java:18)
[26.06 10:04:24] [Server] 	at net.minecraft.class_1255.method_18859(class_1255.java:157)
[26.06 10:04:24] [Server] 	at net.minecraft.class_4093.method_18859(class_4093.java:23)
[26.06 10:04:24] [Server] 	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776)
[26.06 10:04:24] [Server] 	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:160)
[26.06 10:04:24] [Server] 	at net.minecraft.class_1255.method_16075(class_1255.java:131)
[26.06 10:04:24] [Server] 	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758)
[26.06 10:04:24] [Server] 	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752)
[26.06 10:04:24] [Server] 	at net.minecraft.class_1255.method_5383(class_1255.java:116)
[26.06 10:04:24] [Server] 	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:736)
[26.06 10:04:24] [Server] 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669)
[26.06 10:04:24] [Server] 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258)

**Comment by Quplet** [comment]
Hi, thank you for the report. Was your friend, the person being hit, wearing armor? If so, what armor and what enchantments were on them?

If they had unbreaking on any of them, I think I know the cause. I'll be able to push a fix once I get home.
